#pragma once

#ifdef AXLE_TRACING_ENABLE
#define TRACING_ENABLE
#include <Tracer/trace.h>

#define AXLE_TELEMETRY_FUNCTION() STACKTRACE_FUNCTION(); TRACING_FUNCTION()
#define AXLE_TELEMETRY_SCOPE(name) STACKTRACE_SCOPE(name); TRACING_SCOPE(name)
#else
#define AXLE_TELEMETRY_FUNCTION() STACKTRACE_FUNCTION()
#define AXLE_TELEMETRY_SCOPE(name) STACKTRACE_SCOPE(name)
#endif


