#pragma once

//X macro = X(NAME, STRUCTURE)

#define BYTECODES_X \
X(LEAVE_THEN_RETURN)\
X(ENTER_FUNCTION)\
X(CALL_PTR)\
X(CALL_OFFSET)\
X(CALL_R)\
X(MOV_R_TO_R)\
X(MOV_R_TO_M)\
X(MOV_M_TO_R)\
X(MOV_64_TO_R)\
X(MOV_64_TO_M)\
X(PUSH_R)\
X(POP_R)\
X(ADD_R_TO_R)\
X(ADD_64_TO_R)\
X(SUB_R_TO_R)\
X(SUB_64_TO_R)\
X(CMP_R_TO_R)\
X(CMP_64_TO_R)\
X(MUL_R_TO_R)\
X(MUL_64_TO_R)\
X(DIV_R_TO_R)\
X(DIV_64_TO_R)\
X(OR_R_TO_R)\
X(AND_R_TO_R)\
X(JUMP_BY_I64)\
X(JUMP_BY_I64_IF_ZERO)\
X(JUMP_BY_I64_IF_NOT_ZERO)\
X(SET_R_TO_ZF)
