#pragma once

//X macro = X(NAME, STRUCTURE)

#define BYTECODES_X \
X(RETURN, OP)\
X(CALL, OP_64)\
X(LABEL, OP_64)\
X(PUSH_VAL, OP_VAL)\
X(POP_TO_VAL, OP_VAL)\
X(PUSH_FRAME, OP)\
X(POP_FRAME, OP)\
X(COPY_TO_MEM, OP_VAL_VAL)\
X(COPY_FROM_MEM, OP_VAL_VAL)\
X(COPY_TO_VAL, OP_VAL_VAL)\
X(SET_VAL_TO_64, OP_VAL_64)\
X(ADD_VALS, OP_VAL_VAL)\
X(SUB_VALS, OP_VAL_VAL)\
X(MUL_VALS, OP_VAL_VAL)\
X(DIV_VALS, OP_VAL_VAL)\
X(EQ_VALS, OP_VAL_VAL)\
X(OR_VALS, OP_VAL_VAL)\
X(AND_VALS, OP_VAL_VAL)\
X(JUMP_TO_FIXED, OP_64)\
X(JUMP_TO_FIXED_IF_VAL_ZERO, OP_VAL_64)\
X(JUMP_TO_FIXED_IF_VAL_NOT_ZERO, OP_VAL_64)
